Repository Patelzil/E-Book-Hub, pull requests merged in 2022-02, with the labels that each got.

#11 (#10) Added Technology section
  Documentation/ProjectProposal.md
Labels: Medium Priority, Medium Risk, Pull Request, Review

#14 (#4) Uploaded block diagram for core feature 1: User Profile.
  Documentation/ArchitecturalBlockDiagram.md
  Documentation/images/user_login_diagram.png
  Documentation/images/user_logout_diagram.png
  Documentation/images/user_signup_diagram.png
  Documentation/images/user_update_profile_diagram.png
Labels: Medium Priority, Pull Request, Review

#16 Issue#5: Uploaded block diagrams for Buy/rent book
  Documentation/images/Sequence-buyebook.png
  Documentation/images/Sequence-paymentdetails.png
Labels: Pull Request, Review

#18 (#15)Added overall web application interaction Diagram
  Documentation/images/Layer_interaction_Diagram.png
Labels: Medium Risk, Pull Request, Review

#19 (issue#6) Uploaded Architectural diagrams for Search feature
  Documentation/images/filteredSearch.jpg
  Documentation/images/searchQuery-eBook.jpg
Labels: High Priority, High Risk, Pull Request, Review

#20 (#3) Uploaded Meeting Minutes
  Documentation/Meeting_Minutes.md
Labels: documentation, Medium Priority, Medium Risk, Pull Request

#23 (#8) Added user story for extra feature
  Documentation/ProjectProposal.md
Labels: Medium Priority, Pull Request, Review

#24 (#7) updated the architecture diagram for book-club
  Documentation/images/user_create_club.png
  Documentation/images/user_join_club.png
  Documentation/images/usre_chat_feature.png
Labels: Medium Risk, Pull Request, Review

#25 (#22) Added link to the block diagrams
  Documentation/ArchitecturalBlockDiagram.md
Labels: Medium Risk, Diagram, Pull Request, Review

#26 Update with links to meeting minutes and diagrams
  README.md
Labels: documentation, Diagram, Pull Request

#27 Final release for Sprint 1
  Documentation/ArchitecturalBlockDiagram.md
  Documentation/Meeting_Minutes.md
  Documentation/ProjectProposal.md
  Documentation/images/Layer_interaction_Diagram.png
  Documentation/images/Sequence-buyebook.png
  Documentation/images/Sequence-paymentdetails.png
  Documentation/images/filteredSearch.jpg
  Documentation/images/searchQuery-eBook.jpg
  Documentation/images/user_create_club.png
  Documentation/images/user_join_club.png
  Documentation/images/user_login_diagram.png
  Documentation/images/user_logout_diagram.png
  Documentation/images/user_signup_diagram.png
  Documentation/images/user_update_profile_diagram.png
  Documentation/images/usre_chat_feature.png
  README.md
Labels: High Priority, Pull Request, Review

#29 (#28) Branching Strategy added
  BRANCHING_STRATEGY.md
Labels: documentation, Pull Request

#30 Update README.md file with branching strategy link
  README.md
Labels: documentation, High Priority, Pull Request, Review

#31 Merge from developer to main
  BRANCHING_STRATEGY.md
  Documentation/Meeting_Minutes.md
  README.md
Labels: High Priority, High Risk, Pull Request

#60 Issue55 front
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/actions/index.js
  frontend/src/assets/logo.png
  frontend/src/components/home.component.js
  frontend/src/components/login.component.js
  frontend/src/components/navbar.component.js
  frontend/src/components/signup.component.js
  frontend/src/index.js
  frontend/src/reducers/index.js
  frontend/src/reportWebVitals.js
  frontend/src/styles/styles.css
Labels: High Priority, Pull Request, Review

#63 #55 added updated user backed code
  Backend/Controller/userController.js
Labels: Pull Request, Review

#65 fixed the cors error (on get and post requests)
  Backend/app.js
  Backend/package-lock.json
  Backend/package.json
Labels: High Priority, Backend

#66 Issue62 database
  Backend/Controller/bookController.js
  Backend/Controller/userController.js
  Backend/app.js
  Backend/models/userModel.js
  Backend/package.json
  Backend/routes/bookRoutes.js
  Backend/routes/userRoutes.js
  node_modules/.package-lock.json
  node_modules/cors/CONTRIBUTING.md
  node_modules/cors/HISTORY.md
  node_modules/cors/LICENSE
  node_modules/cors/README.md
  node_modules/cors/lib/index.js
  node_modules/cors/package.json
  node_modules/node-fetch/LICENSE.md
  node_modules/node-fetch/README.md
  node_modules/node-fetch/browser.js
  node_modules/node-fetch/lib/index.es.js
  node_modules/node-fetch/lib/index.js
  node_modules/node-fetch/lib/index.mjs
  node_modules/node-fetch/package.json
  node_modules/object-assign/index.js
  node_modules/object-assign/license
  node_modules/object-assign/package.json
  node_modules/object-assign/readme.md
  node_modules/tr46/.npmignore
  node_modules/tr46/index.js
  node_modules/tr46/lib/.gitkeep
  node_modules/tr46/lib/mappingTable.json
  node_modules/tr46/package.json
  node_modules/vary/HISTORY.md
  node_modules/vary/LICENSE
  node_modules/vary/README.md
  node_modules/vary/index.js
  node_modules/vary/package.json
  node_modules/webidl-conversions/LICENSE.md
  node_modules/webidl-conversions/README.md
  node_modules/webidl-conversions/lib/index.js
  node_modules/webidl-conversions/package.json
  node_modules/whatwg-url/LICENSE.txt
  node_modules/whatwg-url/README.md
  node_modules/whatwg-url/lib/URL-impl.js
  node_modules/whatwg-url/lib/URL.js
  node_modules/whatwg-url/lib/public-api.js
  node_modules/whatwg-url/lib/url-state-machine.js
  node_modules/whatwg-url/lib/utils.js
  node_modules/whatwg-url/package.json
  package-lock.json
  package.json
Labels: Medium Priority, Medium Risk, Pull Request, Review

#68 (#67) added code for book API and fixed connection errors
  Backend/Controller/bookController.js
Labels: bug, High Risk, Pull Request, Backend

#74 Issue64
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/online_reading.svg
  frontend/src/components/signup.component.js
  frontend/src/styles/styles.css
Labels: High Priority, Pull Request

#75 (#56) (#35) added code for logging into the system and react form for the same
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/login_page.svg
  frontend/src/components/home.component.js
  frontend/src/components/login.component.js
  frontend/src/components/user.component.js
  frontend/src/styles/styles.css
Labels: Medium Risk, Pull Request, Core Feature, front-end

#79 Issue-78
  Backend/Controller/userController.js
  node_modules/.package-lock.json
  node_modules/cryptr/LICENCE
  node_modules/cryptr/README.md
  node_modules/cryptr/index.js
  node_modules/cryptr/package.json
  node_modules/cryptr/tests/index.js
  package-lock.json
  package.json
Labels: Pull Request
